replicaCount: 1

image:
  repository: 489624945988.dkr.ecr.eu-central-1.amazonaws.com/borrowaboat/borrowaboat
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: borrowaboat.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
