apiVersion: v1
kind: Service
metadata:
  name: borrowaboat
spec:
  selector:
    app: borrowaboat
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: {{ .Values.service.type }}